services:
  php:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - '../apps/back:/usr/src/app'
      - '../.env:/usr/src/app/.env'
    networks:
      - db-net
      - api-net
    restart: unless-stopped
    command: [ "php-fpm" ]
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
      target: dev
    networks:
      - api-net
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/api/nginx.dev.conf:ro
      - ../apps/back/public:/usr/src/app/public
    restart: unless-stopped

  db:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - db-net
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  react:
    build:
      context: ..
      dockerfile: docker/react/Dockerfile
      target: dev
    volumes:
      - ../apps/front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:5173"
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - api-net
    restart: unless-stopped


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - db-net

  swagger:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      URLS: >
        [
          { "name": "API Symfony", "url": "http://localhost:8000/api/doc.json" }
        ]

volumes:
  db-data:

networks:
  db-net:
    driver: bridge
  api-net:
    driver: bridge